// sidebars.js

const sidebars = {
  introduction: [{type: 'autogenerated', dirName: 'introduction'}],
  containers: [{type: 'autogenerated', dirName: 'containers'}],
  kubernetes: [{type: 'autogenerated', dirName: 'kubernetes'}],
  eks: [{type: 'autogenerated', dirName: 'eks'}],
  optimizations: [{type: 'autogenerated', dirName: 'optimizations'}],
};

module.exports = sidebars;
