/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
// sidebars.js

const sidebars = {
  Python: [{type: 'autogenerated', dirName: 'python'}],
  Java: [{type: 'autogenerated', dirName: 'java'}],
};

module.exports = sidebars;