// sidebars.js

const sidebars = {
  introduction: [{type: 'autogenerated', dirName: 'introduction'}],
  containers: [{type: 'autogenerated', dirName: 'containers'}],
  kubernetes: [{type: 'autogenerated', dirName: 'kubernetes'}],
  eks: [{type: 'autogenerated', dirName: 'eks'}],
};

module.exports = sidebars;
